/**:
  ros__parameters:
    usingPowerManagementBoard: true
    verbosity: false
    canInterface: can0
    frequencyScale: 32
    inputWeight: 0.5
    maxPulseWidth: 100
    timeout: 300
    kp: 2.0
    ki: 7.0
    kd: 0.0
    antiWindup: 1
    responseMode: 0
    
    controllers: 2
    
    controller0:
      canID: 0
      gearRatio: 89.0
      encoderRatio: 4096.0
      rpmMax: 90.0
      invertEnc: 1
      drive0: #front right
        channel: 0
        kinematics: [-20.0, -20.0, -6.1]
      drive1: #rear right
        channel: 1
        kinematics: [-20.0, 20.0, -6.1]

    controller1:
      canID: 1
      gearRatio: 89.0
      encoderRatio: 4096.0
      rpmMax: 90.0
      invertEnc: 1
      drive0: #front left
        channel: 0
        kinematics: [20.0, -20.0, -6.1]
      drive1: #rear left
        channel: 1
        kinematics: [20.0, 20.0, -6.1]